defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.http]
        address = ":80"

    [entryPoints.api]
        address = ":8080"

# API definition
# Warning: Enabling API will expose Traefik's configuration.
# It is not recommended in production,
# unless secured by authentication and authorizations
#[api]
#    entryPoint = "api"
#    dashboard = true
#    debug = true

